
italian_flags = {
    "ATALANTA":      "https://img.legaseriea.it/vimages/62cfd69d/atalanta.png?webp&q=70&size=-x135",
    "BOLOGNA":       "https://img.legaseriea.it/vimages/62cef3f6/bologna.png?webp&q=70&size=-x135",
    "CAGLIARI":      "https://img.legaseriea.it/vimages/62cfd202/cagliari.png?webp&q=70&size=-x135",
    "EMPOLI":        "https://img.legaseriea.it/vimages/62cef42e/empoli.png?webp&q=70&size=-x135",
    "FIORENTINA":    "https://img.legaseriea.it/vimages/62cef452/fiorentina.png?webp&q=70&size=-x135",
    "FROSINONE":     "https://img.legaseriea.it/vimages/62cfdfec/frosinone.png?webp&q=70&size=-x135",
    "GENOA":         "https://img.legaseriea.it/vimages/649e8a06/GENOA-1.png?webp&q=70&size=-135",
    "HELLAS VERONA": "https://img.legaseriea.it/vimages/62cfe8b8/colore=BLUE.png?webp&q=70&size=-135",
    "INTER":         "https://img.legaseriea.it/vimages/62cef496/inter.png?webp&q=70&size=-x135",
    "JUVENTUS":      "https://img.legaseriea.it/vimages/62cfda28/colore=BLACK.png?webp&q=70&size=-135",
    "LAZIO":         "https://img.legaseriea.it/vimages/62cef4d5/lazio.png?webp&q=70&size=-x135",
    "LECCE":         "https://img.legaseriea.it/vimages/62cef4f6/lecce.png?webp&q=70&size=-x135",
    "MILAN":         "https://img.legaseriea.it/vimages/62cef513/milan.png?webp&q=70&size=-x135",
    "MONZA":         "https://img.legaseriea.it/vimages/62c6acbd/monza.png?webp&q=70&size=-x135",
    "NAPOLI":        "https://img.legaseriea.it/vimages/62cef532/napoli.png?webp&q=70&size=-x135",
    "ROMA":          "https://img.legaseriea.it/vimages/62cfd5ce/roma.png?webp&q=70&size=-x135",
    "SALERNITANA":   "https://img.legaseriea.it/vimages/62cef553/salernitana.png?webp&q=70&size=-x135",
    "SASSUOLO":      "https://img.legaseriea.it/vimages/62cef590/sassuolo.png?webp&q=70&size=-x135",
    "TORINO":        "https://img.legaseriea.it/vimages/62cef5cb/torino.png?webp&q=70&size=-x135",
    "UDINESE":       "https://img.legaseriea.it/vimages/62cef5e9/udinese.png?webp&q=70&size=-x135",
}        